import Foundation
import OSLog
import SharedLogic
import SwiftData

/// The SwiftData record for a profile. The app's `Room` entity, in effect.
///
/// A class here and a struct in `SharedLogic`, deliberately. `SharedLogic.Profile` is what the
/// domain, the widget extension and eventually the watch app read; it must stay free of
/// SwiftData, which is neither `Sendable` nor available everywhere the domain needs to run. The
/// mapping is six lines and it keeps the persistence choice reversible.
@Model
final class ProfileRecord {

    /// The app's own identifier, stable across a SwiftData `PersistentIdentifier` that is not.
    ///
    /// Widgets, notifications and deep links all address a profile by id and must survive the
    /// store being migrated or rebuilt. `PersistentIdentifier` makes no such promise, and on
    /// Android this is the Room autogenerated primary key that everything already keys on.
    @Attribute(.unique) var profileID: Int64

    var name: String
    var latitude: Double
    var longitude: Double
    var calculationMethodRaw: String
    var asrMadhabRaw: String
    var isGps: Bool
    var sortOrder: Int
    var timezone: String
    var useLocationTimezone: Bool
    var hijriOffset: Int
    var hijriOffsetMonthKey: Int

    init(from profile: Profile) {
        profileID = profile.id
        name = profile.name
        latitude = profile.latitude
        longitude = profile.longitude
        calculationMethodRaw = profile.calculationMethod.rawValue
        asrMadhabRaw = profile.asrMadhab.rawValue
        isGps = profile.isGps
        sortOrder = profile.sortOrder
        timezone = profile.timezone
        useLocationTimezone = profile.useLocationTimezone
        hijriOffset = profile.hijriOffset
        hijriOffsetMonthKey = profile.hijriOffsetMonthKey
    }

    /// The domain value. Unknown raw strings fall back rather than trapping: a store written by
    /// a newer build must not crash an older one, and a profile with an unreadable method is
    /// still a profile the user can see and fix.
    var profile: Profile {
        Profile(
            id: profileID,
            name: name,
            latitude: latitude,
            longitude: longitude,
            calculationMethod: CalculationMethodKey(rawValue: calculationMethodRaw) ?? .mwl,
            asrMadhab: AsrMadhab(rawValue: asrMadhabRaw) ?? .shafii,
            isGps: isGps,
            sortOrder: sortOrder,
            timezone: timezone,
            useLocationTimezone: useLocationTimezone,
            hijriOffset: hijriOffset,
            hijriOffsetMonthKey: hijriOffsetMonthKey
        )
    }

    func apply(_ profile: Profile) {
        name = profile.name
        latitude = profile.latitude
        longitude = profile.longitude
        calculationMethodRaw = profile.calculationMethod.rawValue
        asrMadhabRaw = profile.asrMadhab.rawValue
        isGps = profile.isGps
        sortOrder = profile.sortOrder
        timezone = profile.timezone
        useLocationTimezone = profile.useLocationTimezone
        hijriOffset = profile.hijriOffset
        hijriOffsetMonthKey = profile.hijriOffsetMonthKey
    }
}

/// One prayer's tracked state on one day, for one profile. Mirrors Android's `QazaEntry`.
@Model
final class QazaRecord {
    var profileID: Int64
    var prayerRaw: String
    /// Epoch day, not a `Date`: the entry is about a calendar day in the profile's zone, and
    /// storing an instant would make "was Asr prayed on the 12th" depend on where the phone is.
    var epochDay: Int
    var statusRaw: String
    var updatedAt: Date

    init(profileID: Int64, prayer: Prayer, date: CalendarDate, status: QazaStatus) {
        self.profileID = profileID
        prayerRaw = prayer.rawValue
        epochDay = date.epochDay
        statusRaw = status.rawValue
        updatedAt = .now
    }

    var prayer: Prayer? { Prayer(rawValue: prayerRaw) }
    var status: QazaStatus? { QazaStatus(rawValue: statusRaw) }
    var date: CalendarDate { CalendarDate(epochDay: epochDay) }
}

/// Where the store lives and who can read it.
///
/// The container is in an App Group because the widget extension reads the same profiles the app
/// writes — a widget showing a profile the user deleted is the class of bug Phase 4A exists to
/// catch. When the group container is unavailable the store falls back to the app's own
/// container and says so in the log: a simulator build without the entitlement applied should
/// still run, it just cannot feed a widget.
enum AynamaStore {

    static let appGroupIdentifier = "group.com.aynama.prayertimes"

    static let logger = Logger(subsystem: "com.aynama.prayertimes", category: "store")

    /// True when profiles are being written somewhere the widget extension can read.
    static var isSharedWithExtensions: Bool {
        FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: appGroupIdentifier) != nil
    }

    @MainActor
    static func makeContainer(inMemory: Bool = false) -> ModelContainer {
        let schema = Schema([ProfileRecord.self, QazaRecord.self])
        let configuration: ModelConfiguration =
            if inMemory {
                ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
            } else if isSharedWithExtensions {
                ModelConfiguration(schema: schema, groupContainer: .identifier(appGroupIdentifier))
            } else {
                ModelConfiguration(schema: schema)
            }

        if !inMemory && !isSharedWithExtensions {
            logger.warning(
                """
                App Group \(appGroupIdentifier) is not available — the store is app-private and \
                widgets will not see these profiles. Expected only on an unsigned build.
                """
            )
        }

        do {
            return try ModelContainer(for: schema, configurations: configuration)
        } catch {
            // A store that cannot open is not recoverable in the UI, and continuing with a
            // silently-empty one would look like the user's profiles had been deleted.
            fatalError("could not open the aynama store: \(error)")
        }
    }
}
