import Adhan
import Foundation
import Testing

@testable import SharedLogic

/// The one place the two Adhan ports disagree, pinned so it cannot drift back silently.
///
/// Adhan-Kotlin 1.2.1 (Android) applies `MIDDLE_OF_THE_NIGHT` everywhere. Adhan-Swift 1.5.0
/// applies `HighLatitudeRule.recommended(for:)` when the rule is unset, which is
/// `.seventhOfTheNight` above 48°. ``AdhanWrapper/highLatitudeRule`` pins middle-of-the-night to
/// match Android; these tests prove the pin is doing something, and measure what it is worth,
/// so removing it fails with an explanation rather than with twelve mystery vector deltas.
///
/// Probe values regenerated by `scripts/adhan-parity/generate.py`.
@Suite("High-latitude cross-port divergence")
struct HighLatitudeParityTests {

    let wrapper = AdhanWrapper()

    /// Adhan-Swift with the rule left at its own default — what iOS would ship unpinned.
    func unpinned(
        latitude: Double, longitude: Double, date: CalendarDate, zone: TimeZone
    ) throws -> (fajr: ClockTime, isha: ClockTime) {
        var params = CalculationMethod.muslimWorldLeague.params
        params.madhab = .shafi
        let times = try #require(
            PrayerTimes(
                coordinates: Coordinates(latitude: latitude, longitude: longitude),
                date: DateComponents(year: date.year, month: date.month, day: date.day),
                calculationParameters: params
            )
        )
        return (ClockTime.from(times.fajr, in: zone), ClockTime.from(times.isha, in: zone))
    }

    @Test("above 48 degrees the unpinned Adhan-Swift default diverges from Android by hours")
    func londonDivergesWhenUnpinned() throws {
        let london = CalendarDate(year: 2026, month: 6, day: 21)
        let zone = TimeZone(identifier: "Europe/London")!

        let unpinnedTimes = try unpinned(
            latitude: 51.5074, longitude: -0.1278, date: london, zone: zone
        )
        let pinned = try wrapper.prayerTimes(
            latitude: 51.5074, longitude: -0.1278, date: london, timeZone: zone, method: .mwl
        )

        // Adhan-Kotlin's answer, from test-vectors/prayer-times/mwl.json.
        #expect(pinned.fajr == ClockTime(hour: 1, minute: 2))
        #expect(pinned.isha == ClockTime(hour: 1, minute: 2))

        // And what iOS would have shipped instead. Not a rounding difference — a different day.
        #expect(unpinnedTimes.fajr != pinned.fajr)
        #expect(unpinnedTimes.isha != pinned.isha)
        #expect(minutesApart(unpinnedTimes.fajr, pinned.fajr) > 120)
        #expect(minutesApart(unpinnedTimes.isha, pinned.isha) > 120)
    }

    @Test("below 48 degrees the two ports agree even unpinned")
    func zurichAgreesEitherWay() throws {
        // Zurich is 47.38°N, just under the threshold, so `recommended(for:)` also returns
        // middle-of-the-night and the pin changes nothing. This is what makes the divergence a
        // threshold effect rather than a general disagreement about the algorithm.
        let date = CalendarDate(year: 2026, month: 6, day: 21)
        let zone = TimeZone(identifier: "Europe/Zurich")!

        let unpinnedTimes = try unpinned(latitude: 47.3769, longitude: 8.5417, date: date, zone: zone)
        let pinned = try wrapper.prayerTimes(
            latitude: 47.3769, longitude: 8.5417, date: date, timeZone: zone, method: .mwl
        )

        #expect(unpinnedTimes.fajr == pinned.fajr)
        #expect(unpinnedTimes.isha == pinned.isha)
    }

    @Test("under the pinned rule London's midsummer Fajr and Isha collapse onto one instant")
    func londonCollapsesUnderThePinnedRule() throws {
        // The consequence of matching Android, stated as a test rather than left as a surprise.
        // The timeline already handles a collapsed day (see PrayerTimelineTests), and it is not
        // an Arctic curiosity: it is London, for weeks around midsummer. Whether the product
        // wants this on both platforms is the open question TODOS.md records.
        let zone = TimeZone(identifier: "Europe/London")!
        let times = try wrapper.prayerTimes(
            latitude: 51.5074,
            longitude: -0.1278,
            date: CalendarDate(year: 2026, month: 6, day: 21),
            timeZone: zone,
            method: .mwl
        )
        #expect(times.fajr == times.isha)
    }

    func minutesApart(_ lhs: ClockTime, _ rhs: ClockTime) -> Int {
        let raw = abs(lhs.secondOfDay - rhs.secondOfDay) / 60
        return min(raw, 24 * 60 - raw)
    }
}
